name: Build addon zip

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: packager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # get the source tree
      # Stolen from https://github.com/WeakAuras/WeakAuras2/blob/master/.github/workflows/build.yml
      # should probably be a docker so a lot of this is cached/created once
      - name: Install and run Luacheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck
          exec /home/runner/.luarocks/bin/luacheck DynamicBoxer/ --no-color --config ./DynamicBoxer/.luacheckrc -q
      - name: Get the packager
        run: |
          curl -s https://raw.githubusercontent.com/mooreatv/packager/master/release.sh > ./release.sh
          chmod 755 ./release.sh
      - name: Create Retail Package
        run: ./release.sh -m pkgmeta.yaml -p 323794 -w 25009
        env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      - name: Create BCC Classic Package
        run: ./release.sh -m pkgmeta.yaml -g 2.5.2 -p 323794
        env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      - uses: actions/upload-artifact@master
        with:
          name: DynamicBoxerBuild-${{ github.sha }}
          path: .release/
